trainer:
  lr: 1e-5
  max_epochs: 10 #60
  scheduler_max_lr: 5e-4
  scheduler_steps_per_epochs: 100
loader:
  batch_size: 64
  shuffle: True
  pin_memory: False
  num_workers: 0
  prefetch_factor: 0
logger:
  type: "wandb"
  project: "nanomoe"
  log_model: False
  log_every_n_steps: 1
